version: "3.9"
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=logan
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=fileupload
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: