name: Development Workflow
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Build
        working-directory: backend
        run: go build -v ./...
      - name: Calculate Test Coverage
        working-directory: backend
        run: |
          COVERAGE=`go test -cover ./... | grep coverage: | awk '{print substr($5, 1, length($5)-3)}'`
          echo "COVERAGE IS $COVERAGE"
          COVERAGE_VALUE=$((PATH_COVERAGE))
          echo "COVERAGE VALUE IS $COVERAGE_VALUE"

          if test $COVERAGE_VALUE" -lt 90; then
            echo "TEST COVERAGE THRESHOLD NOT MET: Coverage is $PATH_COVERAGE"
            exit 0
          fi
          done
          echo "Test Coverage Complete"
        